######################################################################
# Automatically generated by qmake (2.01a) ? 9? 17 06:14:10 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Plane.h Cuboid.h Cylinder.h GLWidget.h Object.h 
SOURCES += Plane.cpp Cuboid.cpp Cylinder.cpp GLWidget.cpp Main.cpp

QT += opengl
# DEFINES += _USE_VBO

